### ISSUE TITLE
Mantra: StaleDataException on closed cursor in SoloFocusBoardActivity

### ISSUE THREAD

**Issue by estory1** [cbitstech/Intellicare-Template#11]
Chris Karr
May 5 (1 day ago)

to me 
Sent from my iPad

Begin forwarded message:

From: HockeyApp notification@hockeyapp.net
Date: May 5, 2014 at 11:54:30 AM CDT
To: hockeyapp@audacious-software.com
Subject: New Crash Group for Mantra

Mantra 10000

Platform: Android 
Release Type: Beta

HockeyApp created a new crash group.

Reason: 
java.lang.RuntimeException: Unable to resume activity {edu.northwestern.cbits.intellicare.mantra/edu.northwestern.cbits.intellicare.mantra.activities.SoloFocusBoardActivity}: android.database.StaleDataException: Attempted to access a cursor after it has been closed.

Location: 
android.app.ActivityThread.performResumeActivity, line 2788

**Comment by estory1** [comment]
Need repro steps.

**Comment by audaciouscode** [comment]
Closed open cursor in SingleMantraBoardActivity
