### ISSUE TITLE
Mantra: Find new icon

### ISSUE THREAD

**Issue by audaciouscode** [cbitstech/Intellicare-Template#2]
Current icon looks good as a launcher, but is the same icon as the notification from the built-in Gallery app. We need to find one that's photo-related, but relatively simple. Consult with Chris to get access to his icon library (if you don't have access already) to start the search for a replacement.

**Comment by estory1** [comment]
Completed in commit 1aa7a4e7cc6d5e27e6b75058fe7aab4f8fa9fa5e.
