### ISSUE TITLE
Mantra: Needs Standard Intellicare FAQ

### ISSUE THREAD

**Issue by audaciouscode** [cbitstech/Intellicare-Template#8]
Consult with Chris Brenner & Laurie to find out who wants to be responsible for drafting and managing the text.

**Comment by estory1** [comment]
Added a FAQ here: https://github.com/cbitstech/Intellicare-Template/blob/master/Mantra/assets/www/faq.html

Reached-out to Chris & Laurie via email for future responsibility on this.

**Comment by estory1** [comment]
Chris Brenner replied:

> This has previously been assigned to me. Having said that, I’m knee deep in MedLink and up to my neck in Stepped Care so it will be some time before I get this or really much of anything in Intellicare.
> 
> I have cc:ed Susan because I know some of the RAs have been playing with Intellicare. Maybe they can start?
