### ISSUE TITLE
Mantra: Needs Holo-themed progress bars for downloads

### ISSUE THREAD

**Issue by audaciouscode** [cbitstech/Intellicare-Template#9]
The ContextWrapper class (or whatever we used to style the dialog boxes properly) may be the key to fixing the 2.x style of the progress bars.

**Comment by estory1** [comment]
Tried the ContextWrapper here: https://github.com/cbitstech/Intellicare-Template/blob/f38484dbb608bdb66d537501c12ebbd3e2d40c57/iCope/src/edu/northwestern/cbits/intellicare/icope/ViewCardActivity.java#L68-L70

In the statement on this line in my ProgressActivity: https://github.com/cbitstech/Intellicare-Template/blob/master/Mantra/src/edu/northwestern/cbits/intellicare/mantra/activities/ProgressActivity.java#L209

But the UI appearance didn't change... Would love advice from @audaciouscode. :)
